# Generated by Django 5.2.1 on 2025-05-23 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(help_text='카드 식별자', max_length=100, primary_key=True, serialize=False)),
                ('masked_card_number', models.CharField(help_text='마스킹된 카드번호', max_length=20)),
                ('card_name', models.CharField(help_text='카드상품명', max_length=100)),
                ('card_type', models.CharField(choices=[('01', '신용'), ('02', '체크(직불포함)'), ('03', '소액신용체크')], help_text='카드구분', max_length=20)),
                ('owner_type', models.CharField(choices=[('1', '본인'), ('2', '가족')], help_text='본인/가족 구분', max_length=10)),
                ('org_code', models.CharField(help_text='기관명', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '카드',
                'verbose_name_plural': '카드 목록',
            },
        ),
        migrations.CreateModel(
            name='CardBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_year_month', models.CharField(help_text='청구년월 (YYYYMM)', max_length=6)),
                ('payment_year_month_day', models.CharField(help_text='결제년월일 (YYYYMMDD)', max_length=8)),
                ('payment_date', models.DateField(help_text='결제일')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='월별 청구금액', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '카드 청구서',
                'verbose_name_plural': '카드 청구서 목록',
            },
        ),
        migrations.CreateModel(
            name='CardBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='해당 카드의 청구금액', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(help_text='연결된 청구서', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mydata.cardbill')),
                ('card', models.ForeignKey(help_text='연결된 카드', on_delete=django.db.models.deletion.CASCADE, to='mydata.card')),
            ],
            options={
                'verbose_name': '카드별 청구 상세',
                'verbose_name_plural': '카드별 청구 상세 목록',
                'unique_together': {('card', 'bill')},
            },
        ),
        migrations.AddField(
            model_name='cardbill',
            name='cards',
            field=models.ManyToManyField(related_name='bills', through='mydata.CardBillDetail', to='mydata.card'),
        ),
        migrations.CreateModel(
            name='CardApproval',
            fields=[
                ('approval_number', models.CharField(help_text='승인번호', max_length=50, primary_key=True, serialize=False)),
                ('approval_datetime', models.DateTimeField(help_text='승인일시')),
                ('payment_status', models.CharField(choices=[('01', '승인'), ('02', '승인취소'), ('03', '대기'), ('04', '무승인매입')], help_text='결제상태', max_length=20)),
                ('usage_type', models.CharField(choices=[('01', '신용'), ('02', '체크')], help_text='사용구분', max_length=20)),
                ('merchant_name', models.CharField(help_text='가맹점명(소비처)', max_length=100)),
                ('business_number', models.CharField(blank=True, help_text='사업자등록번호', max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='이용금액', max_digits=15)),
                ('installment_count', models.PositiveSmallIntegerField(default=0, help_text='할부회차 (0은 일시불)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(help_text='연결된 카드', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='mydata.card')),
            ],
            options={
                'verbose_name': '카드 승인내역',
                'verbose_name_plural': '카드 승인내역 목록',
                'indexes': [models.Index(fields=['card', 'approval_datetime'], name='mydata_card_card_id_165905_idx')],
                'unique_together': {('card', 'approval_number')},
            },
        ),
    ]
