# Generated by Django 5.2.1 on 2025-05-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapproval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cardapproval',
            name='approved_num',
            field=models.CharField(help_text='승인번호', max_length=50),
        ),
    ]
