# Generated by Django 5.2.1 on 2025-05-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardbill',
            unique_together=set(),
        ),
    ]
