# Generated by Django 5.2.1 on 2025-05-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='masked_card_number',
        ),
        migrations.AddField(
            model_name='card',
            name='card_num',
            field=models.CharField(default=1, help_text='카드번호', max_length=20),
            preserve_default=False,
        ),
    ]
