# Generated by Django 5.2.1 on 2025-05-27 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbill',
            name='cards',
        ),
        migrations.AddField(
            model_name='cardapproval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='cardbill',
            name='org_code',
            field=models.CharField(default=1, help_text='기관코드', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardbill',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_bills', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardapproval',
            name='approved_num',
            field=models.CharField(help_text='승인번호', max_length=50),
        ),
        migrations.AlterField(
            model_name='cardbill',
            name='bill_year_month',
            field=models.CharField(blank=True, help_text='청구년월 (YYYYMM)', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cardbill',
            name='payment_date',
            field=models.DateField(blank=True, help_text='결제일', null=True),
        ),
        migrations.AlterField(
            model_name='cardbill',
            name='payment_year_month_day',
            field=models.CharField(blank=True, help_text='결제년월일 (YYYYMMDD)', max_length=8, null=True),
        ),
        migrations.DeleteModel(
            name='CardBillDetail',
        ),
    ]
