# Generated by Django 5.2.1 on 2025-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_cardapproval_id_alter_cardapproval_approved_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbill',
            name='payment_date',
            field=models.DateField(blank=True, help_text='결제일', null=True),
        ),
    ]
