# Generated by Django 5.2.1 on 2025-05-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_alter_cardbill_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('01', '신용'), ('02', '체크(직불포함)'), ('03', '소액신용체크')], help_text='카드구분', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner_type',
            field=models.CharField(choices=[('1', '본인'), ('2', '가족')], help_text='본인/가족 구분', max_length=10),
        ),
    ]
