# Generated by Django 5.2.1 on 2025-05-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0002_remove_card_masked_card_number_card_card_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='owner_type',
            new_name='card_member',
        ),
    ]
