# Generated by Django 5.2.1 on 2025-05-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0003_alter_cardbill_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbill',
            name='bill_year_month',
            field=models.CharField(blank=True, help_text='청구년월 (YYYYMM)', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cardbill',
            name='payment_year_month_day',
            field=models.CharField(blank=True, help_text='결제년월일 (YYYYMMDD)', max_length=8, null=True),
        ),
    ]
