# Generated by Django 5.2.1 on 2025-05-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0004_alter_cardbill_bill_year_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbill',
            name='cards',
        ),
        migrations.DeleteModel(
            name='CardBillDetail',
        ),
    ]
