# Generated by Django 5.2.1 on 2025-05-26 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0005_remove_cardbill_cards_delete_cardbilldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbill',
            name='card_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_bills', to='mydata.card'),
            preserve_default=False,
        ),
    ]
