# Generated by Django 5.2.1 on 2025-05-26 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0006_cardbill_card_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbill',
            name='card_id',
        ),
        migrations.AddField(
            model_name='cardbill',
            name='org_code',
            field=models.CharField(default=1, help_text='기관코드', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardbill',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_bills', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
