# Generated by Django 5.2.1 on 2025-05-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(max_length=100)),
                ('ord_num', models.CharField(max_length=100)),
                ('mtrt_int', models.CharField(default=0, max_length=100)),
                ('join_deny', models.CharField(max_length=10)),
                ('prd_type', models.CharField(max_length=10)),
                ('dcls_strt_dat', models.DateTimeField()),
                ('scls_end_dat', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=100)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('rsrv_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('ord_num', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_rates', to='finance_recommend.product')),
            ],
            options={
                'db_table': 'savings_rate',
            },
        ),
    ]
