# Generated by Django 5.2.1 on 2025-05-26 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('CARBON', '탄소배출권')], max_length=10, verbose_name='상품구분')),
                ('bas_dt', models.DateField(db_index=True, verbose_name='기준일자')),
                ('itms_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='품목명')),
                ('clpr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='종가')),
                ('flt_rt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='등락율')),
                ('hipr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='고가')),
                ('lopr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='저가')),
                ('mkp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='시가')),
                ('tr_prc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래대금')),
                ('trqu', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('GOLD', '금')], max_length=10, verbose_name='상품구분')),
                ('itms_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='품목명')),
                ('bas_dt', models.DateField(db_index=True, verbose_name='기준일자')),
                ('clpr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='종가')),
                ('flt_rt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='등락율')),
                ('hipr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='고가')),
                ('lopr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='저가')),
                ('mkp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='시가')),
                ('tr_prc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래대금')),
                ('trqu', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('OIL', '유가')], max_length=10, verbose_name='상품구분')),
                ('bas_dt', models.DateField(db_index=True, verbose_name='기준일자')),
                ('oil_ctg', models.CharField(blank=True, max_length=20, null=True, verbose_name='유종')),
                ('wt_avg_prc_cptn', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='가중평균가격(전체)')),
                ('wt_avg_prc_disc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='가중평균가격(할인)')),
                ('trqu', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래량')),
                ('tr_prc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래대금')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_deny', models.CharField(choices=[(1, '제한없음'), (2, '서민전용'), (3, '일부제한')], max_length=10)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('ord_num', models.CharField(max_length=100)),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('join_member', models.CharField(blank=True, max_length=100, null=True)),
                ('join_way', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_type', models.CharField(max_length=10)),
                ('dcls_strt_dat', models.DateField(null=True)),
                ('dcls_end_dat', models.DateField(null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=100)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('rsrv_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('save_trm', models.CharField(blank=True, max_length=100, null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance_recommend.product')),
            ],
        ),
        migrations.CreateModel(
            name='SpotProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('Gold', '금'), ('Oil', '유가'), ('Carbon', '탄소배출권')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_recommend.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SpotProductBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_recommend.spotproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'spot_product')},
            },
        ),
    ]
