# Generated by Django 5.2.1 on 2025-05-24 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prd_name',
            new_name='fin_prdt_cd',
        ),
        migrations.RemoveField(
            model_name='option',
            name='ord_num',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scls_end_dat',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='dcls_end_dat',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fin_co_subm_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fin_prdt_nm',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='kor_co_nm',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dcls_strt_dat',
            field=models.DateTimeField(null=True),
        ),
    ]
