# Generated by Django 5.2.1 on 2025-05-24 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0002_rename_prd_name_product_fin_prdt_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='prd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finance_recommend.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dcls_end_dat',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dcls_strt_dat',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fin_co_subm_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mtrt_int',
            field=models.TextField(),
        ),
    ]
