# Generated by Django 5.2.1 on 2025-05-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0003_alter_option_prd_alter_product_dcls_end_dat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fin_co_subm_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
