# Generated by Django 5.2.1 on 2025-05-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0004_alter_product_fin_co_subm_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('fin_prdt_cd', 'ord_num')},
        ),
        migrations.AlterModelTable(
            name='option',
            table=None,
        ),
    ]
