# Generated by Django 5.2.1 on 2025-05-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0005_alter_product_unique_together_alter_option_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_cd',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_nm',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('fin_prdt_cd', 'fin_prdt_nm')},
        ),
    ]
