# Generated by Django 5.2.1 on 2025-05-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0006_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('fin_prdt_cd', 'fin_prdt_nm', 'ord_num')},
        ),
    ]
