# Generated by Django 5.2.1 on 2025-05-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0007_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_cd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_nm',
            field=models.CharField(max_length=100),
        ),
    ]
