# Generated by Django 5.2.1 on 2025-05-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0008_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_nm',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
