# Generated by Django 5.2.1 on 2025-05-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0009_alter_product_fin_prdt_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_nm',
            field=models.CharField(max_length=100),
        ),
    ]
