# Generated by Django 5.2.1 on 2025-05-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0010_alter_option_intr_rate_alter_option_intr_rate2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='save_trm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='etc_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='join_member',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='join_way',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spcl_cnd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
