# Generated by Django 5.2.1 on 2025-05-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0011_option_save_trm_product_etc_note_product_join_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='join_deny',
            field=models.CharField(choices=[(1, '제한없음'), (2, '서민전용'), (3, '일부제한')], max_length=10),
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('GOLD', '금'), ('OIL', '유가'), ('CARBON', '탄소배출권')], max_length=10, verbose_name='상품구분')),
                ('bas_dt', models.DateField(db_index=True, verbose_name='기준일자')),
                ('gold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='금 가격')),
                ('oil_ctg', models.CharField(blank=True, max_length=20, null=True, verbose_name='유종')),
                ('wt_avg_prc_cptn', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='가중평균가격(전체)')),
                ('wt_avg_prc_disc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='가중평균가격(할인)')),
                ('trqu', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래량')),
                ('tr_prc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래대금')),
                ('crbn_ctg', models.CharField(blank=True, max_length=50, null=True, verbose_name='탄소배출권 종류')),
                ('crbn_prc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='탄소배출권 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '스팟 가격 정보',
                'verbose_name_plural': '스팟 가격 정보',
                'ordering': ['-bas_dt'],
                'unique_together': {('spot_type', 'bas_dt')},
            },
        ),
    ]
