# Generated by Django 5.2.1 on 2025-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0012_alter_product_join_deny_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('CARBON', '탄소배출권')], max_length=10, verbose_name='상품구분')),
                ('bas_dt', models.DateField(db_index=True, verbose_name='기준일자')),
                ('items_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='품목명')),
                ('clpr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='종가')),
                ('flr_rt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='등락율')),
                ('hipr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='고가')),
                ('lopr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='저가')),
                ('mkp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='시가')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('items_nm', 'bas_dt')},
            },
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('GOLD', '금')], max_length=10, verbose_name='상품구분')),
                ('items_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='품목명')),
                ('bas_dt', models.DateField(db_index=True, verbose_name='기준일자')),
                ('gold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='금 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('bas_dt', 'items_nm')},
            },
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('OIL', '유가')], max_length=10, verbose_name='상품구분')),
                ('bas_dt', models.DateField(db_index=True, verbose_name='기준일자')),
                ('oil_ctg', models.CharField(blank=True, max_length=20, null=True, verbose_name='유종')),
                ('wt_avg_prc_cptn', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='가중평균가격(전체)')),
                ('wt_avg_prc_disc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='가중평균가격(할인)')),
                ('tr_qu', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래량')),
                ('tr_prc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래대금')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('oil_ctg', 'bas_dt')},
            },
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
