# Generated by Django 5.2.1 on 2025-05-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0013_carbon_gold_oil_delete_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbon',
            old_name='flr_rt',
            new_name='flt_rt',
        ),
        migrations.RemoveField(
            model_name='gold',
            name='gold_price',
        ),
        migrations.AddField(
            model_name='gold',
            name='clpr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='종가'),
        ),
        migrations.AddField(
            model_name='gold',
            name='flt_rt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='등락율'),
        ),
        migrations.AddField(
            model_name='gold',
            name='hipr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='고가'),
        ),
        migrations.AddField(
            model_name='gold',
            name='lopr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='저가'),
        ),
        migrations.AddField(
            model_name='gold',
            name='mkp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='시가'),
        ),
        migrations.AddField(
            model_name='gold',
            name='tr_prc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래대금'),
        ),
        migrations.AddField(
            model_name='gold',
            name='trqu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래량'),
        ),
    ]
