# Generated by Django 5.2.1 on 2025-05-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0014_rename_flr_rt_carbon_flt_rt_remove_gold_gold_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbon',
            old_name='items_nm',
            new_name='itms_nm',
        ),
        migrations.AlterUniqueTogether(
            name='carbon',
            unique_together={('itms_nm', 'bas_dt')},
        ),
    ]
