# Generated by Django 5.2.1 on 2025-05-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0015_rename_items_nm_carbon_itms_nm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='items_nm',
            new_name='itms_nm',
        ),
        migrations.AlterUniqueTogether(
            name='gold',
            unique_together={('bas_dt', 'itms_nm')},
        ),
    ]
