# Generated by Django 5.2.1 on 2025-05-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0016_rename_items_nm_gold_itms_nm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='trqu',
            new_name='trQu',
        ),
    ]
