# Generated by Django 5.2.1 on 2025-05-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0017_rename_trqu_gold_trqu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='trQu',
            new_name='tr_qu',
        ),
        migrations.AlterUniqueTogether(
            name='carbon',
            unique_together=set(),
        ),
    ]
