# Generated by Django 5.2.1 on 2025-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0018_rename_trqu_gold_tr_qu_alter_carbon_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='tr_prc',
            new_name='trprc',
        ),
        migrations.RenameField(
            model_name='gold',
            old_name='tr_qu',
            new_name='trqu',
        ),
        migrations.RenameField(
            model_name='oil',
            old_name='tr_prc',
            new_name='trprc',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='tr_qu',
        ),
        migrations.AddField(
            model_name='oil',
            name='trqu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래량'),
        ),
    ]
