# Generated by Django 5.2.1 on 2025-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0019_rename_tr_prc_gold_trprc_rename_tr_qu_gold_trqu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gold',
            old_name='trprc',
            new_name='tr_prc',
        ),
        migrations.RenameField(
            model_name='oil',
            old_name='trprc',
            new_name='tr_prc',
        ),
        migrations.AddField(
            model_name='carbon',
            name='trprc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래대금'),
        ),
        migrations.AddField(
            model_name='carbon',
            name='trqu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='거래량'),
        ),
    ]
