# Generated by Django 5.2.1 on 2025-05-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0020_rename_trprc_gold_tr_prc_rename_trprc_oil_tr_prc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbon',
            old_name='trprc',
            new_name='tr_prc',
        ),
    ]
