# Generated by Django 5.2.1 on 2025-05-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_recommend', '0021_rename_trprc_carbon_tr_prc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gold',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='oil',
            unique_together=set(),
        ),
    ]
