# Generated by Django 5.2.1 on 2025-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name_user_nickname_user_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
